services:
  bind9:
    image: bind9:$VERSION
    hostname: bind9
    container_name: bind9
    restart: always
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./named.conf.local:/etc/bind/named.conf.local
      - ./named.conf.options:/etc/bind/named.conf.options

